language: julia
os:
  - linux
  - osx
julia:
  - nightly
notifications:
  email: 
      - code@donner.at
script:
  - julia -e 'Pkg.init(); Pkg.clone("FunctionalDataUtils")'
  - julia -e 'Pkg.test("FunctionalDataUtils")'
